### ISSUE TITLE
Photo Misaligned

### ISSUE THREAD

**Issue by aryan-vora23** [aarchie-r/surakshIIT#1]
If no profile photo is uploaded during the registration, then the profile page displays the symbol for no image but this symbol is misplaced and aesthetically does not look good.

**Comment by uditpd3000** [comment]
It has been fixed.
If photo is not uploaded then we will see a default profile pic otherwise the uploaded pic.
![Screenshot from 2022-04-21 00-54-35](https://user-images.githubusercontent.com/75174340/164307520-8cd85ec1-e1ce-463b-9c81-3a7f05850ffe.png)
