### ISSUE TITLE
Error Message When UID Does Not Exist for Hall Entry, Lost Items, Found Items

### ISSUE THREAD

**Issue by aryan-vora23** [aarchie-r/surakshIIT#2]
If we enter a UID which is currently not registered in the system, the error message is very vague. We should expect a clear error message stating that the UID does not exist. This causes confusion on the side of the user.

**Comment by uditpd3000** [comment]
This bug has been fixed.
If you enter a UID which is not registered, you will get appropriate error message like this

![Screenshot from 2022-04-21 00-10-23](https://user-images.githubusercontent.com/75174340/164300366-6c949868-aa87-4a1b-8ad4-6848a6cc86ac.png)
