### ISSUE TITLE
Multiple Entries Simultaneously

### ISSUE THREAD

**Issue by aryan-vora23** [aarchie-r/surakshIIT#4]
A person can enter a different hall without exiting from the previous hall. This should ideally not be possible as a person must exit from the previous hall before entering any other hall.

**Comment by uditpd3000** [comment]
This bug has been fixed.
I added a field to keep track if a user is in different hall, if it is the case, then he/she cannot make another hall entry without oerforming hall exit at the earlier hall.

![Screenshot from 2022-04-21 00-07-21](https://user-images.githubusercontent.com/75174340/164299785-235d1938-6b8e-49c2-bf0d-4290a6f4be27.png)

If we try to bypass it, we will get an error message like this
