### ISSUE TITLE
Hall Entry Of Student Who Is Not In Campus

### ISSUE THREAD

**Issue by aryan-vora23** [aarchie-r/surakshIIT#5]
A student who has exit from the campus through the portal can still enter his/her details in the hall entry/exit portal and be allowed to visit the hall. This seems illogical as a person not in the campus should be denied entry in halls.

**Comment by uditpd3000** [comment]
This bug has been fixed. 
I added a field namely 'IsOutOfCampus' to user class which keeps track of every student if he/she is in campus.
Only after checking this he/she will be allowed to perform hall entry or campus entry.

![Screenshot from 2022-04-21 00-04-19](https://user-images.githubusercontent.com/75174340/164299297-63fd119f-eb18-4906-8986-923968967bc7.png)

If we try to bypass this, we will get an error message like this
