### ISSUE TITLE
Empty Fields In Forms Get Submitted

### ISSUE THREAD

**Issue by aryan-vora23** [aarchie-r/surakshIIT#6]
The form for campus non-residents entry gets submitted without any errors even if the ID Card Number field is left blank, this is a fatal flaw as the ID Card is the only identification of campus non-residents and is required by the security to keep track of them.

**Comment by uditpd3000** [comment]
This bug has been fixed.
![Screenshot from 2022-04-20 23-56-09](https://user-images.githubusercontent.com/75174340/164297854-0a845a11-b4aa-4dc1-a3d7-6d9a708b4f20.png)
As you can see if the id number field is not filled, a error message is coming stating 'Fill in the required fields'.
